### ISSUE TITLE
Hossein's Todo

### ISSUE THREAD

**Issue by hosseindehghanipour1998** [ACovaci99/I_Love_Science_Fest#12]
- [x] Set a default value for Scale.
- [x] Add a label next to scale saying "Scale"
- [x] Add QR Code creator code
- [x] Add a Google API code
- [x] Add a Create PDF code to create a PDF from the images produced by the user
- [x] Upload the PDF to Google Drive, Show the QR code to the user
